Indexing / More robust for date type
Avoid indexing error on:
* null date
* invalid date
* upper range bound greater than lower

eg.
```

  Caused by: java.lang.IllegalArgumentException: min value (696902400000) is greater than max value (20191028)

  org.elasticsearch.index.mapper.MapperParsingException: failed to parse field [resourceTemporalDateRange] of type [date_range] in document with id '3e501c87-9146-4d9b-9237-8165c8f7cd51'. Preview of field's value: 'now'

  Caused by: org.elasticsearch.ElasticsearchParseException: failed to parse date field [* date de début de période AAAA[-MM-JJ] *] with format [date_optional_time||yyyy-MM-dd||yyyy-MM||yyyy||epoch_millis]: [failed to parse date field [* date de début de période AAAA[-MM-JJ] *] with format [date_optional_time||yyyy-MM-dd||yyyy-MM||yyyy||epoch_millis]]

org.elasticsearch.index.mapper.MapperParsingException: failed to parse field [resourceTemporalDateRange] of type [date_range] in document with id '6d5020a8-aaae-41c7-b9e2-d3648594ec11'. Preview of field's value: 'null'

```